CREATE DATABASE IF NOT EXISTS book_store;

USE book_store;

CREATE TABLE IF NOT EXISTS books (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

  title VARCHAR(128) NOT NULL,
  author VARCHAR(45) NOT NULL,
  price DECIMAL(8, 2) NOT NULL
);
